services:
  - type: web
    name: ajudajf
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_PASSWORD
        value: ajudajf2024
      - key: DATABASE_URL
        fromDatabase:
          name: ajudajf-db
          property: connectionString

databases:
  - name: ajudajf-db
    databaseName: ajudajf
    plan: free
